### ISSUE TITLE
MutationType Formats etc.

### ISSUE THREAD

**Issue by brucemoran** [QingliGuo/FFPEsig#1]
Hi,

thanks for your work in this area, it is very useful.

I have forked your repo to make some changes to streamline and containerise etc.

Can I ask you for a file instead of hardcoded `ffpe_sig_(un)repaired` arrays in `FFPEsig.py`? 

I am concerned that `MutationType` may be incorrect for the entries from my `input.csv` vs. this array. 

I would like a file of format:
```
MutationType,val
C>A@A_A,2.19310372e-03
C>A@A_C,1.50230572e-03
C>A@A_G,2.24203874e-06
...
```

Thank,

Bruce.

**Comment by QingliGuo** [comment]
Hi Bruce,

Thanks for your words. The file you asked is available here (under 'Data' folder): https://github.com/QingliGuo/FFPEsig/blob/main/Data/FFPE_signatures_96-channel.csv

Best wishes,
Qingli

**Comment by brucemoran** [comment]
Great, thank you!
