### ISSUE TITLE
Tool for signature extraction on corrected profiles and use in WES?

### ISSUE THREAD

**Issue by kmichod** [QingliGuo/FFPEsig#3]
Hello, 

I am wondering what tool you recommend for signature extraction on the FFPE corrected profiles? Any FFPESig specific considerations for use in FFPE WES instead of WGS?

Thank you!

**Comment by QingliGuo** [comment]
Hi! Do you mean signature refitting? You can try FitMS (https://signal.mutationalsignatures.com/analyse2) or SignatureProfiler (https://cancer.sanger.ac.uk/signatures/tools/).

We recommend using FFPEsig on WGS data as the signal (total mutation burden) is much weaker in WES data.
