### ISSUE TITLE
Multiple samples

### ISSUE THREAD

**Issue by marcos-diazg** [QingliGuo/FFPEsig#4]
Thanks for this useful tool! I was wondering if there is a way to run this tool for all samples of a particular mutational matrix without having to specify the sample names. Running one by one is a bit annoying for a large number of samples.

**Comment by QingliGuo** [comment]
Hi! Maybe try to use the bash code below to run all your samples at once (it might take longer). But you need to create a file named `sample_names.txt` for the script. The file should contain all sample names line by line. Hope it works!

```
for sample in `cat sample_names.txt`
do
    python FFPEsig.py [--input|-i] <Path-to-the-DataFrame> [--sample|-s] $sample [--label|-l] <Unrepaired|Repaired> [--output_dir|-o] <Path-of-output-folder>
done
```

**Comment by marcos-diazg** [comment]
Awesome, thanks!
