### ISSUE TITLE
Filter FFPE caused arctifacts from FFPEsig results

### ISSUE THREAD

**Issue by Biojenifer** [QingliGuo/FFPEsig#7]
Hi!

I was wondering if it is possible to employ FFPEsig output to filter from a list of variants those which are more probably arctifacts and, if it is so, how can I do it.

Thanks for this wonderful tool!

**Comment by QingliGuo** [comment]
Hi, I think it is possible. You need to establish the artefact signature in this new setting and then apply FFPEsig to remove the artefacts computationally. We have described some tricky cases in our paper, which might be helpful.

Good luck!
