### ISSUE TITLE
Project description should include input file format

### ISSUE THREAD

**Issue by nurmians** [QingliGuo/FFPEsig#8]
I would like to try out the algorithm but there is no information what the input format should be. VCF file format as input would be very much preferred for this type of algorithm. "standard CSV format dataframe which column names are the sample ID" is not descriptive enough. Pls provide example.

**Comment by nurmians** [comment]
From another closed issue, I found out that input matrices should be generated with https://github.com/AlexandrovLab/SigProfilerMatrixGenerator. Maybe worth mentioning in the readme.md? After a painstaking installation process I was able to run it but it only produces tab-separated tables... I guess figuring out which of these files and in what format I can use them with FFPEsig is the next exercise.

**Comment by QingliGuo** [comment]
The input file of FFPEsig consists of the observed mutational profile from the FFPE file, which includes noise. The output file, on the other hand, provides the noise-extracted mutational profile. This allows you to determine the presence of known biological signatures within the FFPE sample. Both files are provided in CSV format. For more detailed information, please refer to our test data.
